protected/models/Calificacion.php
<?php

Yii::import('application.models._base.BaseCalificacion');

class Calificacion extends BaseCalificacion
{
        public $fecha_evaluacion;
        public $observacion_evaluacion;
        
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}
  
        public static function representingColumn() {
		return 'NombreRepresentativo';
	}
                
        public function getNombreRepresentativo(){
                return Alumno::model()->findByPk($this->alumno_id)->nombre;
        }
        
        public static function calificaciones_alumno($alumno_id,$curso_id){
            
            $criteria=new CDbCriteria(array(
                'with' => array('evaluacion'),
                'select'=>'t.id, evaluacion.nombre as nombre , evaluacion.fecha as fecha_evaluacion, evaluacion.observacion as observacion_evaluacion, t.nota',
                'condition'=>'t.alumno_id = :alumno_id and evaluacion.curso_id = :curso_id',
                'order'=>'evaluacion.fecha ASC',
                'params'=> array(':alumno_id' => $alumno_id, ':curso_id'=>$curso_id, ),
             ));
            
            $dataProvider=new CActiveDataProvider('Calificacion',array('criteria'=>$criteria,));	

            return ($dataProvider);
        }
        
}

protected/controllers/AcademicoController.php
<?php

class AcademicoController extends GxController {

        public function filters() {
                return array('rights');
        }

	public function actionIndex() {
                $this->redirect(array('misCursos'));
	}

        public function actionPanel(){
                //$profesor = $this->obtenerProfesor();
                $this->redirect(array('misCursos'));
        }
        
        public function actionMisCursos(){
            
                $profesor = $this->obtenerProfesor();
                $dataProvider=new CActiveDataProvider('Curso', array(
                    'criteria'=>array(
                        'condition'=>'estado = "ACTIVO" and profesor_id='.$profesor->id,
                        'order'=>'anio DESC, semestre DESC',
                    ),
                    'pagination'=>array(
                        'pageSize'=>20,
                    ),
                ));
		$this->render('curso/misCursos', array(
			'dataProvider' => $dataProvider,
		));
        }
        
        /**
         * 
         * @param int $id Curso
         */
	public function actionLibroCurso($id) {
                $this->validarProfesor($id, Yii::t('app', 'Usted no puede ver el libro de este curso.'), true);
                $this->layout='column1';
                $session = new CHttpSession;
                $session->open();
		$model = new LibroCurso('search');
		$model->unsetAttributes();

		if (isset($_GET['LibroCurso'])){
			$model->setAttributes($_GET['LibroCurso']);
                }
                $model->curso_id = $id;
                $session['LibroCurso_model_search'] = $model;
                
		$this->render('curso/libroCurso', array(
			'model' => $model,
		));
	}
        
        /**
         * 
         * @param int $id Curso
         */
        public function actionVerCurso($id){
                $model = $this->validarProfesor($id, Yii::t('app', 'Usted no puede ver este curso.'), true);
		$this->render('curso/verCurso', array(
			'model' => $model,
		));
        }
        
        /**
         * 
         * @param int $id Curso
         */
	public function actionListarPlanActividad($id) {
                $this->validarProfesor($id, Yii::t('app', 'Usted no puede ver los planes de actividades.'));
		$dataProvider = new CActiveDataProvider('PlanActividad', array(
                    'criteria'=>array(
                        'condition'=>'curso_id='.$id,
                        'order'=>'id',
                    ),
                    'countCriteria'=>array(
                        'condition'=>'curso_id='.$id,
                        // 'order' and 'with' clauses have no meaning for the count query
                    ),
                    'pagination'=>array(
                        'pageSize'=>20,
                    ),
                ));
		$this->render('planActividad/listarPlanActividad', array(
			'dataProvider' => $dataProvider,
		));
	}            
        
        /**
         * 
         * @param int $id PlanActvidad
         */
	public function actionVerPlanActividad($id) {
                $model = $this->loadModel($id, 'PlanActividad');
                $this->validarProfesor($model->curso_id, Yii::t('app', 'Usted no puede ver este plan de actividad.'));
                
		$this->render('planActividad/verPlanActividad', array(
			'model' => $model,
		));
	}        
        
        /**
         * 
         * @param int $id Curso
         */
	public function actionCrearPlanActividad($id){
                $this->validarProfesor($id, Yii::t('app', 'Usted no puede crear un plan de actividad para este curso.'));
                $model = new PlanActividad;
                $model_curso= $this->loadModel($id, 'Curso');
                $model->curso_id = $id;
                
                $model_planificacion_semestral = PlanificacionSemestral::model()->vigente($model_curso->anio,$model_curso->semestre)->find();
                if($model_planificacion_semestral != null){
                    $model->planificacion_semestral_id = $model_planificacion_semestral->id;
                }else{
                    $model_planificacion_semestral = PlanificacionSemestral::model();
                    Yii::app()->user->setFlash(TbHtml::ALERT_COLOR_WARNING,
                        Yii::t('app', '<h4>¡Atención!</h4> No se ha definido una '.PlanificacionSemestral::label().', por lo que no va a poder crear un '. PlanActividad::label() .'.'));
 
                
                }
                
		$this->performAjaxValidation($model, 'plan-actividad-form');
		if (isset($_POST['PlanActividad'])) {
			$model->setAttributes($_POST['PlanActividad']);
                        $model->planificacion_semestral_id = $model_planificacion_semestral->id;
			if ($this->validarFechas($model, $model_planificacion_semestral) && $model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('verPlanActividad', 'id' => $model->id));
                                }
		}

		$this->render('planActividad/crearPlanActividad', array( 'model' => $model, 'model_planificacion_semestral' => $model_planificacion_semestral));
	}

        /**
         * 
         * @param int $id PlanActividad
         */
	public function actionEditarPlanActividad($id) {
                $model = $this->loadModel($id, 'PlanActividad');
                $this->validarProfesor($model->curso->id, Yii::t('app', 'Usted no puede editar este plan de actividad para este curso.'));
                $model->curso_id = $model->curso->id;
                
                $model_planificacion_semestral = PlanificacionSemestral::obtenerVigente();
                $model->planificacion_semestral_id = $model_planificacion_semestral->id;
                
		$this->performAjaxValidation($model, 'plan-actividad-form');

		if (isset($_POST['PlanActividad'])) {
			$model->setAttributes($_POST['PlanActividad']);
                        $model->planificacion_semestral_id = $model_planificacion_semestral->id;
			if ($this->validarFechas($model, $model_planificacion_semestral) && $model->save()) {
				$this->redirect(array('verPlanActividad', 'id' => $model->id));
			}
		}

		$this->render('planActividad/editarPlanActividad', array(
				'model' => $model,
                                'model_planificacion_semestral' => $model_planificacion_semestral
				));
	}

        /**
         * 
         * @param int $id PlanActividad
         * @throws CHttpException
         */
	public function actionBorrarPlanActividad($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
                        $model = $this->loadModel($id, 'PlanActividad');
                        $this->validarProfesor($model->curso_id, Yii::t('app', 'Usted no puede borrar este plan de actividad'));
                        $model->delete();
			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('verCurso', 'id' => $model->curso_id));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}        
        
        /**
         * 
         * @param int $id Evaluación
         */
        public function actionVerEvaluacion($id){
                $model = $this->loadModel($id, 'Evaluacion');
                $this->validarProfesor($model->curso_id, Yii::t('app', 'Usted no puede ver esta evaluación.'));                
		$this->render('evaluacion/verEvaluacion', array(
			'model' => $model,
		));
        }
        
        /**
         * 
         * @param int $id Curso
         */
	public function actionCrearEvaluacion($id) {        
                $this->validarProfesor($id, Yii::t('app', 'Usted no puede crear una evaluación para este curso.'));  
                $model = new Evaluacion;
                $model->curso_id = $id;
                
		$this->performAjaxValidation($model, 'evaluacion-form');

		if (isset($_POST['Evaluacion'])) {
			$model->setAttributes($_POST['Evaluacion']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('verEvaluacion', 'id' => $model->id));
			}
		}

		$this->render('evaluacion/crearEvaluacion', array( 'model' => $model));
	}

        /**
         * 
         * @param int $id Evaluación
         */
	public function actionEditarEvaluacion($id) {
		$model = $this->loadModel($id, 'Evaluacion');
                $this->validarProfesor($model->curso_id, Yii::t('app', 'Usted no puede editar esta evaluación para este curso.'));   
                
		$this->performAjaxValidation($model, 'evaluacion-form');

		if (isset($_POST['Evaluacion'])) {
			$model->setAttributes($_POST['Evaluacion']);
                        
			if ($model->save()) {
				$this->redirect(array('verEvaluacion', 'id' => $model->id));
			}
		}

		$this->render('evaluacion/editarEvaluacion', array(
				'model' => $model,
				));
	}
        
        /**
         * 
         * @param int $id Evaluación
         * @throws CHttpException
         */
	public function actionBorrarEvaluacion($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$model = $this->loadModel($id, 'Evaluacion');
                        $curso_id = $model->curso_id;
                        $this->validarProfesor($curso_id, Yii::t('app', 'Usted no puede borrar esta evaluación para este curso.'));
                        $model->delete();
			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('verCurso', 'id' => $curso_id));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}
        
        /**
         * 
         * @param int $id Calificación
         */
	public function actionVerCalificacion($id) {
                $model = $this->loadModel($id, 'Calificacion');
                $this->validarProfesor($model->curso_id, Yii::t('app', 'Usted no puede ver esta calificación.'));   
		$this->render('calificacion/verCalificacion', array(
			'model' => $model,

protected/views/academico/calificacion/_formCalificacion.php

<?php $form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
        'id' => 'calificacion-form',
        'layout'=>TbHtml::FORM_LAYOUT_HORIZONTAL,
        'enableAjaxValidation' => true,
));
?>

	<p class="help-block">
		<?php echo Yii::t('app', 'Fields with'); ?> <span class="required">*</span> <?php echo Yii::t('app', 'are required'); ?>.
	</p>

	<?php echo $form->errorSummary($model); ?>

		<?php echo $form->dropDownListControlGroup($model,'alumno_id', GxHtml::listDataEx(Alumno::model()->curso($model->curso_id)->sinCalificacion($model->evaluacion_id)->findAll()), array('class'=>'span3 selectpicker', 'empty'=>'', 'placeholder'=> Yii::t('app', 'Select') ));?>       
		<?php echo $form->textFieldControlGroup($model,'nota', array('span'=>3, 'maxlength'=>11)); ?>

<?php echo TbHtml::formActions(array(
    TbHtml::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Save'), array('type'=>TbHtml::BUTTON_TYPE_LINK, 'color' => TbHtml::BUTTON_COLOR_PRIMARY, 'id'=>'buttonStateful', 'data-loading-text'=>  Yii::t('app', 'Loading...'))),
    TbHtml::resetButton(Yii::t('app', 'Reset')),
));
?>     
<?php $this->endWidget(); ?>        
<?php $this->widget('ext.select2.ESelect2'); ?>
<?php Yii::app()->clientScript->registerScriptFile(Yii::app()->request->baseUrl.'/js/buttonReset.js', CClientScript::POS_END); ?>
<?php Yii::app()->clientScript->registerScriptFile(Yii::app()->request->baseUrl.'/js/buttonStateful.js', CClientScript::POS_END); ?>
<?php if(!$model->isNewRecord)
Yii::app()->clientScript->registerScript('script_fc',
        '$("#'.GxHtml::activeId($model,'alumno_id').'").select2("enable", false);',
        CClientScript::POS_READY);?>

protected/views/academico/calificacion/_vistaCalificacion.php
<a class="buttonwell" href="<?php echo Yii::app()->controller->createUrl('ver', array('id' => $data->id));?>">
<div class="view well">

	<?php echo GxHtml::encode($data->getAttributeLabel('id')); ?>:
        <?php echo GxHtml::encode($data->id); ?>
	<br />

	<?php echo GxHtml::encode($data->getAttributeLabel('alumno_id')); ?>:
		<?php echo GxHtml::encode(GxHtml::valueEx($data->alumno)); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('evaluacion_id')); ?>:
		<?php echo GxHtml::encode(GxHtml::valueEx($data->evaluacion)); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('curso_id')); ?>:
		<?php echo GxHtml::encode(GxHtml::valueEx($data->curso)); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('nota')); ?>:
        <?php echo GxHtml::encode($data->nota); ?>
	<br />

</div>
</a>

protected/views/academico/calificacion/crearCalificacion.php
<?php

$this->breadcrumbs = array(
       Yii::app()->user->profesor => Yii::app()->createUrl('academico/panel'),
       GxHtml::encode(Curso::label(2))=> Yii::app()->createUrl('academico/misCursos'),
        GxHtml::valueEx($model->curso)=>Yii::app()->createUrl('academico/verCurso', array('id'=>$model->curso->id)),
        GxHtml::valueEx($model->evaluacion)=>Yii::app()->createUrl('academico/verEvaluacion', array('id'=>$model->evaluacion->id)),
	Yii::t('app', 'Create'). ' ' . $model->label(1),
);

$this->menu = array(
//        array('label'=>Yii::t('app', 'Operations')),
//        array('label'=>Yii::t('app', 'List') . ' ' . $model->label(2), 'url' => array('listar'), 'icon'=>'list'),
//        array('label'=>Yii::t('app', 'Manage') . ' ' . $model->label(2), 'url' => array('administrar'), 'icon'=>'list-alt'),
        array('label'=>Yii::t('app', 'Other|Others', 2)),
        array('label'=>Yii::t('app', 'Back'), 'url'=>'javascript:history.back()', 'icon'=>'arrow-left'),
);
?>

<?php echo TbHtml::pageHeader(Yii::t('app', 'Create') . ' ' . GxHtml::encode($model->label()), null); ?>
<?php
$this->renderPartial('calificacion/_formCalificacion', array(
		'model' => $model,
		'buttons' => 'create'));
?>

protected/views/academico/calificacion/editarCalificacion.php
<?php

$this->breadcrumbs = array(
        Yii::app()->user->profesor => Yii::app()->createUrl('academico/panel'),
        GxHtml::encode(Curso::label(2))=> Yii::app()->createUrl('academico/misCursos'),
        GxHtml::valueEx($model->evaluacion->curso)=>Yii::app()->createUrl('academico/verCurso', array('id'=>$model->evaluacion->curso->id)),
        GxHtml::valueEx($model->evaluacion)=>Yii::app()->createUrl('academico/verEvaluacion', array('id'=>$model->evaluacion->id)),
	GxHtml::valueEx($model) => array('academico/verCalificacion', 'id' => GxActiveRecord::extractPkValue($model, true)),
	Yii::t('app', 'Update'),
);

$this->menu = array(       
//        array('label'=>Yii::t('app', 'Operations')),
//        array('label' => Yii::t('app', 'List') . ' ' . $model->label(2), 'url'=>array('listar'), 'icon'=>'list'),
//        array('label' => Yii::t('app', 'Create') . ' ' . $model->label(), 'url'=>array('crear'), 'icon'=>'file'),
//        array('label' => Yii::t('app', 'View') . ' ' . $model->label(), 'url'=>array('ver', 'id' => GxActiveRecord::extractPkValue($model, true)), 'icon'=>'eye-open'),
//        array('label' => Yii::t('app', 'Manage') . ' ' . $model->label(2), 'url'=>array('administrar'), 'icon'=>'list-alt'),
        array('label'=>Yii::t('app', 'Other|Others', 2)),
        array('label'=>Yii::t('app', 'Back'), 'url'=>'javascript:history.back()', 'icon'=>'arrow-left'),
);
?>

<?php echo TbHtml::pageHeader(Yii::t('app', 'Update') . ' ' . GxHtml::encode($model->label()) . ' ' . GxHtml::encode(GxHtml::valueEx($model)), null); ?>

<?php
$this->renderPartial('calificacion/_formCalificacion', array(
		'model' => $model));
?>

protected/views/academico/calificacion/listarCalificacion.php
<?php

$this->breadcrumbs = array(
        Yii::app()->user->profesor => Yii::app()->createUrl('academico/panel'),
	Calificacion::label(2),
);

$this->menu = array(
        array('label'=>Yii::t('app', 'Operations')),
        array('label'=>Yii::t('app', 'Create') . ' ' . Calificacion::label(), 'url' => array('crear'), 'icon'=>'file'),
        array('label'=>Yii::t('app', 'Manage') . ' ' . Calificacion::label(2), 'url' => array('administrar'), 'icon'=>'list-alt'),
        array('label'=>Yii::t('app', 'Other|Others', 2)),
        array('label'=>Yii::t('app', 'Back'), 'url'=>'javascript:history.back()', 'icon'=>'arrow-left'),
        array('label'=>Yii::t('app', 'Up'), 'url'=>'javascript:GoUp()', 'icon'=>'arrow-up', 'id'=>'button-up'),
);
?>
<?php echo TbHtml::pageHeader(GxHtml::encode(Calificacion::label(2)), null); ?>

<?php $this->widget('bootstrap.widgets.TbListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'calificacion/_vista',
)); ?>
<?php Yii::app()->clientScript->registerScriptFile(Yii::app()->request->baseUrl . '/js/scroll.js'); ?>

protected/views/academico/calificacion/verCalificacion.php
<?php

$this->breadcrumbs = array(
       Yii::app()->user->profesor => Yii::app()->createUrl('academico/panel'),
       GxHtml::encode(Curso::label(2))=> Yii::app()->createUrl('academico/misCursos'),
       GxHtml::valueEx($model->evaluacion->curso)=>Yii::app()->createUrl('academico/verCurso', array('id'=>$model->evaluacion->curso->id)),
       GxHtml::valueEx($model->evaluacion)=>Yii::app()->createUrl('academico/verEvaluacion', array('id'=>$model->evaluacion->id)),
       GxHtml::valueEx($model),
);

$this->menu=array(
        array('label'=>Yii::t('app', 'Operations')),
//        array('label'=>Yii::t('app', 'List') . ' ' . $model->label(2), 'url'=>array('academico/listarCalificacion'), 'icon'=>'list'),
//        array('label'=>Yii::t('app', 'Create') . ' ' . $model->label(), 'url'=>array('academico/crearCalificacion'), 'icon'=>'file'),
        array('label'=>Yii::t('app', 'Update') . ' ' . $model->label(), 'url'=>array('academico/editarCalificacion', 'id' => $model->id), 'icon'=>'pencil'),
        array('label'=>Yii::t('app', 'Delete') . ' ' . $model->label(), 'url'=>'#', 'linkOptions' => array('submit' => array('academico/borrarCalificacion', 'id' => $model->id), 'confirm'=>Yii::t('app', 'Are you sure you want to delete this item?')), 'icon'=>'trash'),
//        array('label'=>Yii::t('app', 'Manage') . ' ' . $model->label(2), 'url'=>array('administrar'), 'icon'=>'list-alt'),
        array('label'=>Yii::t('app', 'Other|Others', 2)),
        array('label'=>Yii::t('app', 'Back'), 'url'=>'javascript:history.back()', 'icon'=>'arrow-left'),
);
?>

<?php echo TbHtml::pageHeader(Yii::t('app', 'View') . ' ' . GxHtml::encode($model->label()) . ' ' . GxHtml::encode(GxHtml::valueEx($model)), null); ?>

<?php $this->widget('bootstrap.widgets.TbDetailView', array(
	'data' => $model,
	'attributes' => array(
		'id',
		array(
			'name' => 'alumno',
			'type' => 'raw',
			'value' => $model->alumno !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->alumno)), array('academico/verAlumno', 'id' => GxActiveRecord::extractPkValue($model->alumno, true), 'curso_id' => GxActiveRecord::extractPkValue($model->curso, true))) : null,
			),
		array(
			'name' => 'evaluacion',
			'type' => 'raw',
			'value' => $model->evaluacion !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->evaluacion)), array('academico/verEvaluacion', 'id' => GxActiveRecord::extractPkValue($model->evaluacion, true), 'curso_id'=>$model->evaluacion->curso_id)) : null,
			),
		array(
			'name' => 'curso',
			'type' => 'raw',
			'value' => $model->curso !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->curso)), array('academico/verCurso', 'id' => GxActiveRecord::extractPkValue($model->curso, true))) : null,
			),
		'nota',
	),
)); ?>