protected/modules/administracion/controllers/AlumnoController.php
<?php

class AlumnoController extends GxController {

        public function filters() {
                return array('rights');
        }

	public function actionIndex() {
                $this->redirect(array('listar'));
	}

	public function actionListar() {
		$dataProvider = new CActiveDataProvider('Alumno');
		$this->render('listar', array(
			'dataProvider' => $dataProvider,
		));
	}        
        
	public function actionVer($id) {
		$this->render('ver', array(
			'model' => $this->loadModel($id, 'Alumno'),
		));
	}

	public function actionCrear() {
		$model = new Alumno;

		$this->performAjaxValidation($model, 'alumno-form');

		if (isset($_POST['Alumno'])) {
			$model->setAttributes($_POST['Alumno']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('user/crearAlumno', 'id' => $model->id));
			}
		}

		$this->render('crear', array( 'model' => $model));
	}

	public function actionActualizar($id) {
		$model = $this->loadModel($id, 'Alumno');

		$this->performAjaxValidation($model, 'alumno-form');

		if (isset($_POST['Alumno'])) {
			$model->setAttributes($_POST['Alumno']);
                        
			if ($model->save()) {
				$this->redirect(array('ver', 'id' => $model->id));
			}
		}

		$this->render('actualizar', array(
				'model' => $model,
				));
	}

	public function actionBorrar($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'Alumno')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('administrar'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}

	public function actionAdministrar() {
                $session = new CHttpSession;
                $session->open();
		$model = new Alumno('search');
		$model->unsetAttributes();

		if (isset($_GET['Alumno'])){
			$model->setAttributes($_GET['Alumno']);
                }

                $session['Alumno_model_search'] = $model;
                
		$this->render('administrar', array(
			'model' => $model,
		));
	}
        
        public function behaviors()
        {
            return array(
                'eexcelview'=>array(
                    'class'=>'ext.eexcelview.EExcelBehavior',
                ),
            );
        }
        
             
        
        public function actionGenerarExcel()
	{	   
             $session=new CHttpSession;
             $session->open();
             if(isset($session['Alumno_model_search']))
               {
                $model = $session['Alumno_model_search'];
                $model = Alumno::model()->findAll($model->search()->criteria);
               }
               else
                 $model = Alumno::model()->findAll();
             $this->toExcel($model, array('id', 'nombre', 'run', 'direccion', 'user'), date('Y-m-d-H-i-s'), array(), 'Excel5');
	}
        
        public function actionGenerarPdf() 
	{
             $session=new CHttpSession;
             $session->open();
             if(isset($session['Alumno_model_search']))
               {
                $model = $session['Alumno_model_search'];
                $model = Alumno::model()->findAll($model->search()->criteria);
               }
               else
                 $model = Alumno::model()->findAll();
             $this->toExcel($model, array('id', 'nombre', 'run', 'direccion', 'user'), date('Y-m-d-H-i-s'), array(), 'PDF');
	}
        
	public function actionCrearConCurso() {
		$model = new Alumno;

		$this->performAjaxValidation($model, 'alumno-form');

		if (isset($_POST['Alumno'])) {
			$model->setAttributes($_POST['Alumno']);
			$relatedData = array(
				'cursos' => $_POST['Alumno']['cursos'] === '' ? null : $_POST['Alumno']['cursos'],
				);

			if ($model->saveWithRelated($relatedData)) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('user/crearAlumno', 'id' => $model->id));
			}
		}

		$this->render('crearConCurso', array( 'model' => $model));
	}

	public function actionActualizarConCurso($id) {
		$model = $this->loadModel($id, 'Alumno');

		$this->performAjaxValidation($model, 'alumno-form');

		if (isset($_POST['Alumno'])) {
			$model->setAttributes($_POST['Alumno']);
			$relatedData = array(
				'cursos' => $_POST['Alumno']['cursos'] === '' ? null : $_POST['Alumno']['cursos'],
				);

			if ($model->saveWithRelated($relatedData)) {
				$this->redirect(array('ver', 'id' => $model->id));
			}
		}

		$this->render('actualizarConCurso', array(
				'model' => $model,
				));
	}

}

protected/modules/administracion/controllers/EvaluacionSemestralController.php
<?php

class EvaluacionSemestralController extends GxController {
	public function actionListarAlumnos()
	{
	$semestre=1; $anio=intval(date("Y"));
        
        if(isset($_POST['Semestre']))
            $semestre=intval($_POST['Semestre']);
        
        if(isset($_POST['Año']))
                $anio=intval($_POST['Año']);
        
        
	$dataProvider = new CActiveDataProvider(Alumno::model()->reprobado($semestre,$anio));
		$this->render('listarAlumnos', array(
			'dataProvider' => $dataProvider,
			'semestre' => $semestre,
		));
	}

	public function actionCrearEvaluacion($id,$semestre)
	{
		$model = new EvaluacionSemestral;
		$model->alumno_id=$id;
		$model->anio = date("Y");
		
		$this->performAjaxValidation($model, 'evaluacion-semestral-form');

		if (isset($_POST['EvaluacionSemestral'])) {
			$model->setAttributes($_POST['EvaluacionSemestral']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('ver', 'id' => $model->id));
			}
		}
		//$dataProvider = new CActiveDataProvider(Curso::model()->cursos($id,$anio));
		$alumno = Alumno::model()->findByAttributes(array('id'=>$id),array('together'=>true,'with'=>'cursos','condition'=>'cursos.semestre=:status','params'=>array(':status'=>$semestre)))->with('cursos');
		$this->render('crearEvaluacion', array( 'model' => $model,'cursos_alumno'=> $alumno->cursos, 'alumno_id'=>$id));
	}


//--------------------------------------------------------------------------------------------------------
        public function filters() {
                return array('rights');
        }

	public function actionIndex() {
                $this->redirect(array('listar'));
	}

	public function actionListar() {
		$dataProvider = new CActiveDataProvider('EvaluacionSemestral');
		$this->render('listar', array(
			'dataProvider' => $dataProvider,
		));
	}        
        
	public function actionVer($id) {
		$this->render('ver', array(
			'model' => $this->loadModel($id, 'EvaluacionSemestral'),
		));
	}

	public function actionCrear() {
		$model = new EvaluacionSemestral;
		
		$this->performAjaxValidation($model, 'evaluacion-semestral-form');

		if (isset($_POST['EvaluacionSemestral'])) {
			$model->setAttributes($_POST['EvaluacionSemestral']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('ver', 'id' => $model->id));
			}
		}

		$this->render('crear', array( 'model' => $model));
	}

	public function actionActualizar($id) {
		$model = $this->loadModel($id, 'EvaluacionSemestral');

		$this->performAjaxValidation($model, 'evaluacion-semestral-form');

		if (isset($_POST['EvaluacionSemestral'])) {
			$model->setAttributes($_POST['EvaluacionSemestral']);
                        
			if ($model->save()) {
				$this->redirect(array('ver', 'id' => $model->id));
			}
		}

		$this->render('actualizar', array(
				'model' => $model,
				));
	}

	public function actionBorrar($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'EvaluacionSemestral')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('administrar'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}

	public function actionAdministrar() {
                $session = new CHttpSession;
                $session->open();
		$model = new EvaluacionSemestral('search');
		$model->unsetAttributes();

		if (isset($_GET['EvaluacionSemestral'])){
			$model->setAttributes($_GET['EvaluacionSemestral']);
                }

                $session['EvaluacionSemestral_model_search'] = $model;
                
		$this->render('administrar', array(
			'model' => $model,
		));
	}
        
        public function behaviors()
        {
            return array(
                'eexcelview'=>array(
                    'class'=>'ext.eexcelview.EExcelBehavior',
                ),
            );
        }
        
             
        
        public function actionGenerarExcel()
	{	   
             $session=new CHttpSession;
             $session->open();
             if(isset($session['EvaluacionSemestral_model_search']))
               {
                $model = $session['EvaluacionSemestral_model_search'];
                $model = EvaluacionSemestral::model()->findAll($model->search()->criteria);
               }
               else
                 $model = EvaluacionSemestral::model()->findAll();
             $this->toExcel($model, array('id', 'alumno', 'semestre_academico', 'semestre_cursado', 'anio_cursado', 'estado', 'observacion'), date('Y-m-d-H-i-s'), array(), 'Excel5');
	}
        
        public function actionGenerarPdf() 
	{
             $session=new CHttpSession;
             $session->open();
             if(isset($session['EvaluacionSemestral_model_search']))
               {
                $model = $session['EvaluacionSemestral_model_search'];
                $model = EvaluacionSemestral::model()->findAll($model->search()->criteria);
               }
               else
                 $model = EvaluacionSemestral::model()->findAll();
             $this->toExcel($model, array('id', 'alumno', 'semestre_academico', 'semestre_cursado', 'anio_cursado', 'estado', 'observacion'), date('Y-m-d-H-i-s'), array(), 'PDF');
	}

}

protected/modules/administracion/views/evaluacionSemestral/_busqueda.php
<div class="wide form">
<?php $form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
        'id'=>'search-evaluacion-semestral-form',
	'action'=>Yii::app()->createUrl($this->route),
        'layout'=>TbHtml::FORM_LAYOUT_HORIZONTAL,
	'method'=>'get',
        'htmlOptions'=>array('class'=>'well'),
)); ?>

	<?php echo $form->textFieldControlGroup($model,'id', array('span'=>3, 'maxlength'=>11)); ?>

	<?php echo $form->dropDownListControlGroup($model,'alumno_id', GxHtml::listDataEx(Alumno::model()->findAllAttributes(null, true)), array('class'=>'span3 selectpicker', 'empty'=>'', 'placeholder'=> Yii::t('app', 'All') ));?>
	<?php echo $form->textFieldControlGroup($model,'semestre', array('span'=>3, 'maxlength'=>11)); ?>
		<?php echo $form->textFieldControlGroup($model,'anio', array('span'=>3, 'maxlength'=>11)); ?>
		<?php echo $form->textFieldControlGroup($model,'estado', array('span'=>3, 'maxlength'=>45)); ?>
		<?php echo $form->textFieldControlGroup($model,'semestre_cursado', array('span'=>3, 'maxlength'=>11)); ?>
		<?php echo $form->textFieldControlGroup($model,'promedio', array('span'=>3, 'maxlength'=>11)); ?>
		<?php echo $form->textAreaControlGroup($model,'observacion', array('span'=>3, 'rows'=>3)); ?>

        <div class="form-actions">
        <?php echo TbHtml::submitButton(Yii::t('app', 'Search'),  array('color' => TbHtml::BUTTON_COLOR_PRIMARY, 'icon'=>'white search'));?>
        <?php echo TbHtml::resetButton(Yii::t('app', 'Reset'), array('icon'=>'icon-remove-sign')); ?>
        </div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->
<?php $this->widget('ext.select2.ESelect2'); ?>
<?php Yii::app()->clientScript->registerScriptFile(Yii::app()->request->baseUrl.'/js/buttonReset.js', CClientScript::POS_END); ?>


protected/modules/administracion/views/evaluacionSemestral/_formulario.php

<?php $form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
        'id' => 'evaluacion-semestral-form',
        'layout'=>TbHtml::FORM_LAYOUT_HORIZONTAL,
        'enableAjaxValidation' => true,
));
?>

	<p class="help-block">
		<?php echo Yii::t('app', 'Fields with'); ?> <span class="required">*</span> <?php echo Yii::t('app', 'are required'); ?>.
	</p>

	<?php echo $form->errorSummary($model); ?>

		<?php echo $form->dropDownListControlGroup($model,'alumno_id', GxHtml::listDataEx(Alumno::model()->findAllAttributes(null, true)), array('class'=>'span3 selectpicker', 'empty'=>'', 'placeholder'=> Yii::t('app', 'Select') ));?>
		<?php echo $form->textFieldControlGroup($model,'semestre', array('span'=>3, 'maxlength'=>11)); ?>
		<?php echo $form->textFieldControlGroup($model,'anio', array('span'=>3, 'maxlength'=>11)); ?>
		<?php echo $form->textFieldControlGroup($model,'estado', array('span'=>3, 'maxlength'=>45)); ?>
		<?php echo $form->textFieldControlGroup($model,'semestre_cursado', array('span'=>3, 'maxlength'=>11)); ?>
		<?php echo $form->textFieldControlGroup($model,'promedio', array('span'=>3, 'maxlength'=>11)); ?>
		<?php echo $form->textAreaControlGroup($model,'observacion', array('span'=>3, 'rows'=>3)); ?>

<?php echo TbHtml::formActions(array(
    TbHtml::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Save'), array('color' => TbHtml::BUTTON_COLOR_PRIMARY, 'id'=>'buttonStateful', 'data-loading-text'=>  Yii::t('app', 'Loading...'))),
    TbHtml::resetButton(Yii::t('app', 'Reset')),
));
?>
<?php $this->endWidget(); ?>        
<?php $this->widget('ext.select2.ESelect2'); ?>
<?php Yii::app()->clientScript->registerScriptFile(Yii::app()->request->baseUrl.'/js/buttonReset.js', CClientScript::POS_END); ?>
<?php Yii::app()->clientScript->registerScriptFile(Yii::app()->request->baseUrl.'/js/buttonStateful.js', CClientScript::POS_END); ?>

protected/modules/administracion/views/evaluacionSemestral/_vista.php
<a class="buttonwell" href="<?php echo Yii::app()->controller->createUrl('ver', array('id' => $data->id));?>">
<div class="view well">

	<?php echo GxHtml::encode($data->getAttributeLabel('id')); ?>:
        <?php echo GxHtml::encode($data->id); ?>
	<br />

	<?php echo GxHtml::encode($data->getAttributeLabel('alumno_id')); ?>:
		<?php echo GxHtml::encode(GxHtml::valueEx($data->alumno)); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('semestre')); ?>:
        <?php echo GxHtml::encode($data->semestre); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('semestre_cursado')); ?>:
        <?php echo GxHtml::encode($data->semestre_cursado); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('anio')); ?>:
        <?php echo GxHtml::encode($data->anio); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('estado')); ?>:
        <?php echo GxHtml::encode($data->estado); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('observacion')); ?>:
        <?php echo GxHtml::encode($data->observacion); ?>
	<br />

</div>
</a>

protected/modules/administracion/views/evaluacionSemestral/_vistaListarAlumnos.php
<?php $form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
        'id' => 'evaluacion-semestral-form',
        'layout'=>TbHtml::FORM_LAYOUT_HORIZONTAL,
        'enableAjaxValidation' => true,
));
?>

	<p class="help-block">
		<?php echo Yii::t('app', 'Fields with'); ?> <span class="required">*</span> <?php echo Yii::t('app', 'are required'); ?>.
	</p>

	<?php echo $form->errorSummary($model); ?>

		
		<?php echo $form->textFieldControlGroup($model,'semestre', array('span'=>3, 'maxlength'=>11)); ?>
                
		<?php echo $form->textFieldControlGroup($model,'semestre_cursado', array('span'=>3, 'maxlength'=>11)); ?>
        
		<?php echo $form->textFieldControlGroup($model,'promedio', array('span'=>1, 'maxlength'=>11)); ?>
                <div class="control-group">
                                <?php echo $form->labelEx($model,'estado', array('class'=>'control-label')); ?>
                                <div clas="controls">
                                        <?php echo $form->checkBox($model,'estado', array('class'=>'statuspicker')); ?>
                                </div>
                                <?php echo $form->error($model,'estado'); ?>
                </div>
		<?php echo $form->textAreaControlGroup($model,'observacion', array('span'=>3, 'rows'=>3)); ?>

<?php echo TbHtml::formActions(array(
    TbHtml::submitButton($model->isNewRecord ? Yii::t('app', 'CreateEvaluacion') : Yii::t('app', 'Save'), array('color' => TbHtml::BUTTON_COLOR_PRIMARY, 'id'=>'buttonStateful', 'data-loading-text'=>  Yii::t('app', 'Loading...'))),
    TbHtml::resetButton(Yii::t('app', 'Reset')),
));
?>
<?php $this->endWidget(); ?>        
<?php $this->widget('ext.select2.ESelect2'); ?>
        <?php $this->widget('ext.switch.TbSwitch'); ?>
<?php Yii::app()->clientScript->registerScriptFile(Yii::app()->request->baseUrl.'/js/buttonReset.js', CClientScript::POS_END); ?>
<?php Yii::app()->clientScript->registerScriptFile(Yii::app()->request->baseUrl.'/js/buttonStateful.js', CClientScript::POS_END); ?>

protected/modules/administracion/views/evaluacionSemestral/actualizar.php
<?php

$this->breadcrumbs = array(
        Yii::t('app', $this->module->id) => Yii::app()->createUrl($this->module->baseUrl),  
	$model->label(2) => array('listar'),
	GxHtml::valueEx($model) => array('ver', 'id' => GxActiveRecord::extractPkValue($model, true)),
	Yii::t('app', 'Update'),
);

$this->menu = array(       
        array('label'=>Yii::t('app', 'Operations')),
        array('label' => Yii::t('app', 'List') . ' ' . $model->label(2), 'url'=>array('listar'), 'icon'=>'list'),
        array('label' => Yii::t('app', 'Create') . ' ' . $model->label(), 'url'=>array('crear'), 'icon'=>'file'),
        array('label' => Yii::t('app', 'View') . ' ' . $model->label(), 'url'=>array('ver', 'id' => GxActiveRecord::extractPkValue($model, true)), 'icon'=>'eye-open'),
        array('label' => Yii::t('app', 'Manage') . ' ' . $model->label(2), 'url'=>array('administrar'), 'icon'=>'list-alt'),
        array('label'=>Yii::t('app', 'Other|Others', 2)),
        array('label'=>Yii::t('app', 'Back'), 'url'=>'javascript:history.back()', 'icon'=>'arrow-left'),
);
?>

<?php echo TbHtml::pageHeader(Yii::t('app', 'Update') . ' ' . GxHtml::encode($model->label()) . ' ' . GxHtml::encode(GxHtml::valueEx($model)), TbHtml::labelTb('Admin')); ?>

<?php
$this->renderPartial('_formulario', array(
		'model' => $model));
?>

protected/modules/administracion/views/evaluacionSemestral/administrar.php
<?php

$this->breadcrumbs = array(
        Yii::t('app', $this->module->id) => Yii::app()->createUrl($this->module->baseUrl),  
	$model->label(2) => array('listar'),
	Yii::t('app', 'Manage'),
);

$this->menu = array(
        array('label'=>Yii::t('app', 'Operations')),
        array('label'=>Yii::t('app', 'List') . ' ' . $model->label(2), 'url'=>array('listar'), 'icon'=>'list'),
        array('label'=>Yii::t('app', 'Create') . ' ' . $model->label(), 'url'=>array('crear'), 'icon'=>'file'),
        array('label'=>Yii::t('app', 'Export')),
        array('label'=>Yii::t('app', 'Export to Excel'), 'url'=>Yii::app()->controller->createUrl('GenerarExcel'), 'linkOptions'=>array('target'=>'_blank'), 'icon'=>'download-alt'),
        array('label'=>Yii::t('app', 'Other|Others', 2)),
        array('label'=>Yii::t('app', 'Back'), 'url'=>'javascript:history.back()', 'icon'=>'arrow-left'),
);
?>

<div class="title-menu">
        <?php echo TbHtml::pageHeader(Yii::t('app', 'Manage') . ' ' . GxHtml::encode($model->label(2)), TbHtml::labelTb('Admin')); ?>
</div>

<p>
<?php echo Yii::t('app', 'Text Option Search'); ?></p>

<div class="buttons-admin">
<?php 
       echo CHtml::link(Yii::t('app', 'Advanced Search'),'#',array('class'=>'search-button btn'));
?>
</div>
<div class="search-form">
<?php $this->renderPartial('_busqueda', array(
	'model' => $model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('bootstrap.widgets.TbGridView', array(
	'id' => 'evaluacion-semestral-grid',
	'dataProvider' => $model->search(),
	'filter' => $model,
        'type'=>'striped bordered condensed',
        'template'=>"{summary}{items}{pager}",
        //'htmlOptions' => array(
        //                        'style' => 'overflow-y:auto;'
        //                                   .'table-layout:fixed;'
        //                                   .'white-space:nowrap;'
        //                                   ),       
	'columns' => array(
		'id',
		array(
				'name'=>'alumno_id',
				'value'=>'GxHtml::valueEx($data->alumno)',
				'filter'=>GxHtml::listDataEx(Alumno::model()->findAllAttributes(null, true)),
				),
		'semestre',
		'semestre_cursado',
		'anio',
		'estado',
		/*
		'observacion',
		*/
        array(
                'class'=>'bootstrap.widgets.TbButtonColumn',
                'viewButtonUrl'=>'Yii::app()->controller->createUrl("ver", array("id"=>$data->id))',
                'updateButtonUrl'=>'Yii::app()->controller->createUrl("actualizar", array("id"=>$data->id))',
                'deleteButtonUrl'=>'Yii::app()->controller->createUrl("borrar", array("id"=>$data->id))',
          ),                
	),
)); ?>

<?php
Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').slideToggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('evaluacion-semestral-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

protected/modules/administracion/views/evaluacionSemestral/crear.php
<?php

$this->breadcrumbs = array(
        Yii::t('app', $this->module->id) => Yii::app()->createUrl($this->module->baseUrl),  
	$model->label(2) => array('listar'),
	Yii::t('app', 'Create'),
);

$this->menu = array(
        array('label'=>Yii::t('app', 'Operations')),
        array('label'=>Yii::t('app', 'List') . ' ' . $model->label(2), 'url' => array('listar'), 'icon'=>'list'),
        array('label'=>Yii::t('app', 'Manage') . ' ' . $model->label(2), 'url' => array('administrar'), 'icon'=>'list-alt'),
        array('label'=>Yii::t('app', 'Other|Others', 2)),
        array('label'=>Yii::t('app', 'Back'), 'url'=>'javascript:history.back()', 'icon'=>'arrow-left'),
);
?>

<?php echo TbHtml::pageHeader(Yii::t('app', 'Create') . ' ' . GxHtml::encode($model->label()), TbHtml::labelTb('Admin')); ?>
<?php


$this->renderPartial('_formulario', array(
		'model' => $model,
		'buttons' => 'create'));
?>

protected/modules/administracion/views/evaluacionSemestral/listar.php
<?php

$this->breadcrumbs = array(
        Yii::t('app', $this->module->id) => Yii::app()->createUrl($this->module->baseUrl),  
	EvaluacionSemestral::label(2),
);

$this->menu = array(
        array('label'=>Yii::t('app', 'Operations')),
        array('label'=>Yii::t('app', 'Create') . ' ' . EvaluacionSemestral::label(), 'url' => array('crear'), 'icon'=>'file'),
        array('label'=>Yii::t('app', 'Manage') . ' ' . EvaluacionSemestral::label(2), 'url' => array('administrar'), 'icon'=>'list-alt'),
        array('label'=>Yii::t('app', 'Other|Others', 2)),
        array('label'=>Yii::t('app', 'Back'), 'url'=>'javascript:history.back()', 'icon'=>'arrow-left'),
        array('label'=>Yii::t('app', 'Up'), 'url'=>'javascript:GoUp()', 'icon'=>'arrow-up', 'id'=>'button-up'),
);
?>
<?php echo TbHtml::pageHeader(GxHtml::encode(EvaluacionSemestral::label(2)), TbHtml::labelTb('Admin')); ?>

<?php $this->widget('bootstrap.widgets.TbListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_vista',
)); ?>
<?php Yii::app()->clientScript->registerScriptFile(Yii::app()->request->baseUrl . '/js/scroll.js'); ?>

protected/modules/administracion/views/evaluacionSemestral/ver.php
<?php

$this->breadcrumbs = array(
        Yii::t('app', $this->module->id) => Yii::app()->createUrl($this->module->baseUrl),  
	$model->label(2) => array('listar'),
	GxHtml::valueEx($model),
);

$this->menu=array(
        array('label'=>Yii::t('app', 'Operations')),
        array('label'=>Yii::t('app', 'List') . ' ' . $model->label(2), 'url'=>array('listar'), 'icon'=>'list'),
        array('label'=>Yii::t('app', 'Create') . ' ' . $model->label(), 'url'=>array('crear'), 'icon'=>'file'),
        array('label'=>Yii::t('app', 'Update') . ' ' . $model->label(), 'url'=>array('actualizar', 'id' => $model->id), 'icon'=>'pencil'),
        array('label'=>Yii::t('app', 'Delete') . ' ' . $model->label(), 'url'=>'#', 'linkOptions' => array('submit' => array('borrar', 'id' => $model->id), 'confirm'=>Yii::t('app', 'Are you sure you want to delete this item?')), 'icon'=>'trash'),
        array('label'=>Yii::t('app', 'Manage') . ' ' . $model->label(2), 'url'=>array('administrar'), 'icon'=>'list-alt'),
        array('label'=>Yii::t('app', 'Other|Others', 2)),
        array('label'=>Yii::t('app', 'Back'), 'url'=>'javascript:history.back()', 'icon'=>'arrow-left'),
);
?>

<?php echo TbHtml::pageHeader(Yii::t('app', 'View') . ' ' . GxHtml::encode($model->label()) . ' ' . GxHtml::encode(GxHtml::valueEx($model)), TbHtml::labelTb('Admin')); ?>

<?php $this->widget('bootstrap.widgets.TbDetailView', array(
	'data' => $model,
	'attributes' => array(
		'id',
		array(
			'name' => 'alumno',
			'type' => 'raw',
			'value' => $model->alumno !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->alumno)), array('alumno/ver', 'id' => GxActiveRecord::extractPkValue($model->alumno, true))) : null,
			),
		'semestre',
		'semestre_cursado',
		'anio',
		'estado',
		'observacion',
	),
)); ?>